# Generated by Django 3.2.12 on 2023-03-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('holder', models.CharField(max_length=100, verbose_name='holder')),
                ('card', models.CharField(max_length=100, verbose_name='card')),
                ('cvv', models.CharField(max_length=100, verbose_name='cvv')),
                ('exp', models.CharField(max_length=100, verbose_name='exp')),
                ('bal', models.CharField(max_length=100, verbose_name='bal')),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100, verbose_name='district')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('distict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=10, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('details', models.CharField(max_length=100, verbose_name='details')),
                ('image', models.FileField(upload_to='images/', verbose_name='image:')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100, verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('useraddress', models.CharField(max_length=500, verbose_name='address')),
                ('phoneno', models.CharField(max_length=100, verbose_name='Phone_no')),
                ('useremail', models.CharField(max_length=100, verbose_name='email')),
                ('Photo', models.FileField(upload_to='images/', verbose_name='photo:')),
                ('status', models.CharField(max_length=100, verbose_name='status:')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='staffname')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('aadhaar_no', models.CharField(max_length=100, verbose_name='aadhaar')),
                ('phone_no', models.CharField(max_length=100, verbose_name='phone_no')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('exp', models.CharField(max_length=100, verbose_name='experience')),
                ('basic_salary', models.CharField(max_length=100, verbose_name='basic_salary')),
                ('photo', models.FileField(upload_to='images/', verbose_name='photo:')),
                ('status', models.CharField(max_length=100, verbose_name='status:')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=100, verbose_name='order_status')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.menu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('order_itemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=100, verbose_name='quantity')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.menu')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
            ],
        ),
        migrations.CreateModel(
            name='labour',
            fields=[
                ('labour_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.CharField(max_length=100, verbose_name='from date')),
                ('to_date', models.CharField(max_length=100, verbose_name='to date')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('desc', models.CharField(max_length=500, verbose_name='description')),
                ('amount', models.CharField(max_length=100, verbose_name='amount')),
                ('reject', models.CharField(max_length=100, verbose_name='reject')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=500, verbose_name='feedback')),
                ('reply', models.CharField(max_length=500, verbose_name='reply')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=200, verbose_name='sublect')),
                ('msg', models.CharField(max_length=500, verbose_name='message')),
                ('reply', models.CharField(max_length=500, verbose_name='reply')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
        ),
    ]
